import React from "react";

type Props = {
  imageName: string;
};

const ImageData = (props: Props) => {
  return (
    <div>
      <h2>Image Data</h2>
      <p>Image Name: {props.imageName}</p>
      <p>Dummy Data: Generated by a fake API call</p>
    </div>
  );
};

export default ImageData;